// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA33mXXRIMHGtRnz5MPDesI59Z6X3pr368',
    appId: '1:712800017677:web:91c10efb18ec5de870e444',
    messagingSenderId: '712800017677',
    projectId: 'crm-app-ba7b3',
    authDomain: 'crm-app-ba7b3.firebaseapp.com',
    storageBucket: 'crm-app-ba7b3.firebasestorage.app',
    measurementId: 'G-M5VF4324VR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYRgDAwnm3UaKIcpD3zCEl_MWghHOfqNk',
    appId: '1:712800017677:android:f7000709d9b9afc670e444',
    messagingSenderId: '712800017677',
    projectId: 'crm-app-ba7b3',
    storageBucket: 'crm-app-ba7b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHRS4xlihYxvKnzB8xX1cN5Eaz7snNdqI',
    appId: '1:712800017677:ios:4fb381781477e1bc70e444',
    messagingSenderId: '712800017677',
    projectId: 'crm-app-ba7b3',
    storageBucket: 'crm-app-ba7b3.firebasestorage.app',
    iosBundleId: 'com.example.crmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHRS4xlihYxvKnzB8xX1cN5Eaz7snNdqI',
    appId: '1:712800017677:ios:4fb381781477e1bc70e444',
    messagingSenderId: '712800017677',
    projectId: 'crm-app-ba7b3',
    storageBucket: 'crm-app-ba7b3.firebasestorage.app',
    iosBundleId: 'com.example.crmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA33mXXRIMHGtRnz5MPDesI59Z6X3pr368',
    appId: '1:712800017677:web:9df60a64e1444c9070e444',
    messagingSenderId: '712800017677',
    projectId: 'crm-app-ba7b3',
    authDomain: 'crm-app-ba7b3.firebaseapp.com',
    storageBucket: 'crm-app-ba7b3.firebasestorage.app',
    measurementId: 'G-CL9SRBBNMJ',
  );
}
